In [1]:
import pandas as pd
from tqdm import tqdm

In [2]:
!pwd

/Users/bzhang/code/accurateair_project/accurateair/data-process/04-model

In [3]:
path1 = '../../data/air_data/pm25_2016_all_cities.csv'

In [4]:
data = pd.read_csv(path1)

In [5]:
data

,new_date,date,hour,type,Beijing,Tianjin,Tangshan,Baoding,Zhangjiakou,Chengde,...,Zhaotong,Lijiang,Lincang,Qamdo,Nyingchi,Hanzhong,Yulin,Ankang,Zhangye,Jiuquan
0,2016-01-01 00:00:00,20160101,0,PM2.5,171.0,169.0,NaN,NaN,73.0,75.0,...,74.0,11.0,15.0,49.0,8.0,202.0,116.0,207.0,53.0,66.0
1,2016-01-01 01:00:00,20160101,1,PM2.5,167.0,161.0,279.0,301.0,53.0,78.0,...,93.0,16.0,24.0,3.0,5.0,203.0,119.0,202.0,47.0,44.0
2,2016-01-01 02:00:00,20160101,2,PM2.5,158.0,150.0,261.0,321.0,47.0,64.0,...,150.0,13.0,25.0,4.0,4.0,199.0,118.0,208.0,38.0,43.0
3,2016-01-01 03:00:00,20160101,3,PM2.5,147.0,137.0,198.0,303.0,43.0,58.0,...,52.0,20.0,36.0,1.0,15.0,188.0,122.0,219.0,30.0,33.0
4,2016-01-01 04:00:00,20160101,4,PM2.5,134.0,126.0,162.0,211.0,40.0,59.0,...,52.0,19.0,30.0,2.0,10.0,190.0,94.0,194.0,25.0,26.0
5,2016-01-01 05:00:00,20160101,5,PM2.5,115.0,130.0,160.0,190.0,37.0,62.0,...,50.0,21.0,23.0,2.0,8.0,188.0,99.0,192.0,21.0,21.0
6,2016-01-01 06:00:00,20160101,6,PM2.5,105.0,127.0,156.0,177.0,41.0,62.0,...,35.0,22.0,21.0,4.0,5.0,186.0,93.0,217.0,20.0,15.0
7,2016-01-01 07:00:00,20160101,7,PM2.5,102.0,127.0,144.0,158.0,41.0,60.0,...,34.0,19.0,20.0,5.0,5.0,190.0,94.0,217.0,21.0,11.0
8,2016-01-01 08:00:00,20160101,8,PM2.5,104.0,128.0,149.0,148.0,50.0,64.0,...,37.0,16.0,17.0,20.0,6.0,187.0,102.0,221.0,26.0,7.0
9,2016-01-01 09:00:00,20160101,9,PM2.5,107.0,128.0,164.0,144.0,63.0,90.0,...,37.0,17.0,25.0,13.0,3.0,199.0,149.0,214.0,29.0,12.0
10,2016-01-01 10:00:00,20160101,10,PM2.5,115.0,138.0,157.0,144.0,64.0,97.0,...,30.0,23.0,28.0,19.0,9.0,205.0,176.0,215.0,34.0,14.0
11,2016-01-01 11:00:00,20160101,11,PM2.5,122.0,147.0,156.0,138.0,54.0,88.0,...,16.0,16.0,30.0,26.0,8.0,205.0,106.0,255.0,30.0,26.0
12,2016-01-01 12:00:00,20160101,12,PM2.5,134.0,153.0,163.0,129.0,47.0,80.0,...,16.0,19.0,32.0,29.0,14.0,187.0,78.0,261.0,27.0,25.0
13,2016-01-01 13:00:00,20160101,13,PM2.5,148.0,148.0,167.0,145.0,53.0,85.0,...,18.0,24.0,39.0,34.0,12.0,145.0,73.0,234.0,22.0,151.0
14,2016-01-01 14:00:00,20160101,14,PM2.5,167.0,158.0,168.0,162.0,59.0,82.0,...,24.0,22.0,45.0,36.0,8.0,116.0,58.0,197.0,11.0,69.0
15,2016-01-01 15:00:00,20160101,15,PM2.5,178.0,191.0,196.0,190.0,90.0,82.0,...,31.0,17.0,42.0,6.0,8.0,98.0,53.0,140.0,6.0,50.0
16,2016-01-01 16:00:00,20160101,16,PM2.5,186.0,194.0,225.0,209.0,109.0,112.0,...,42.0,15.0,41.0,29.0,9.0,82.0,51.0,123.0,7.0,50.0
17,2016-01-01 17:00:00,20160101,17,PM2.5,192.0,202.0,239.0,246.0,124.0,140.0,...,51.0,16.0,33.0,24.0,10.0,78.0,54.0,127.0,6.0,45.0
18,2016-01-01 18:00:00,20160101,18,PM2.5,219.0,221.0,262.0,286.0,122.0,162.0,...,74.0,16.0,35.0,42.0,8.0,88.0,66.0,157.0,15.0,41.0
19,2016-01-01 19:00:00,20160101,19,PM2.5,246.0,232.0,273.0,314.0,128.0,179.0,...,66.0,18.0,33.0,48.0,10.0,118.0,113.0,153.0,29.0,61.0
20,2016-01-01 20:00:00,20160101,20,PM2.5,262.0,243.0,258.0,310.0,117.0,187.0,...,75.0,14.0,36.0,109.0,17.0,161.0,121.0,167.0,53.0,76.0
21,2016-01-01 21:00:00,20160101,21,PM2.5,279.0,256.0,244.0,340.0,109.0,183.0,...,63.0,22.0,30.0,75.0,14.0,175.0,123.0,174.0,45.0,100.0
22,2016-01-01 22:00:00,20160101,22,PM2.5,270.0,262.0,266.0,378.0,88.0,176.0,...,60.0,23.0,27.0,44.0,18.0,178.0,148.0,151.0,49.0,65.0
23,2016-01-01 23:00:00,20160101,23,PM2.5,275.0,268.0,283.0,408.0,80.0,158.0,...,49.0,20.0,28.0,31.0,8.0,158.0,137.0,126.0,81.0,33.0
24,2016-01-02 00:00:00,20160102,0,PM2.5,284.0,283.0,296.0,483.0,75.0,164.0,...,45.0,23.0,23.0,16.0,7.0,145.0,142.0,117.0,91.0,32.0
25,2016-01-02 01:00:00,20160102,1,PM2.5,284.0,289.0,309.0,509.0,65.0,161.0,...,41.0,22.0,21.0,11.0,7.0,129.0,123.0,110.0,48.0,34.0
26,2016-01-02 02:00:00,20160102,2,PM2.5,267.0,295.0,312.0,502.0,57.0,149.0,...,43.0,22.0,18.0,9.0,8.0,124.0,106.0,103.0,42.0,30.0
27,2016-01-02 03:00:00,20160102,3,PM2.5,247.0,296.0,333.0,526.0,54.0,146.0,...,35.0,20.0,18.0,9.0,6.0,129.0,126.0,93.0,36.0,33.0
28,2016-01-02 04:00:00,20160102,4,PM2.5,221.0,300.0,351.0,424.0,50.0,142.0,...,39.0,17.0,21.0,22.0,3.0,121.0,114.0,93.0,30.0,35.0
29,2016-01-02 05:00:00,20160102,5,PM2.5,206.0,304.0,356.0,345.0,51.0,145.0,...,35.0,16.0,18.0,37.0,3.0,111.0,107.0,90.0,30.0,29.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8548,2016-12-30 17:00:00,20161230,17,PM2.5,253.0,210.0,198.0,235.0,63.0,66.0,...,50.0,12.0,5.0,18.0,13.0,86.0,47.0,89.0,13.0,19.0
8549,2016-12-30 18:00:00,20161230,18,PM2.5,292.0,213.0,213.0,270.0,94.0,90.0,...,55.0,16.0,10.0,32.0,13.0,91.0,55.0,101.0,16.0,17.0
8550,2016-12-30 19:00:00,20161230,19,PM2.5,307.0,216.0,224.0,283.0,84.0,106.0,...,69.0,9.0,17.0,43.0,11.0,127.0,73.0,127.0,26.0,30.0
8551,2016-12-30 20:00:00,20161230,20,PM2.5,298.0,219.0,211.0,273.0,100.0,107.0,...,90.0,14.0,21.0,96.0,11.0,159.0,78.0,122.0,26.0,59.0
8552,2016-12-30 21:00:00,20161230,21,PM2.5,287.0,221.0,228.0,276.0,82.0,87.0,...,71.0,18.0,24.0,121.0,9.0,190.0,74.0,115.0,138.0,66.0
8553,2016-12-30 22:00:00,20161230,22,PM2.5,299.0,222.0,234.0,282.0,73.0,98.0,...,169.0,22.0,28.0,119.0,10.0,219.0,67.0,102.0,82.0,62.0
8554,2016-12-30 23:00:00,20161230,23,PM2.5,281.0,226.0,238.0,289.0,60.0,87.0,...,137.0,11.0,21.0,59.0,9.0,208.0,68.0,103.0,62.0,56.0
8555,2016-12-31 00:00:00,20161231,0,PM2.5,277.0,223.0,256.0,297.0,52.0,86.0,...,85.0,24.0,23.0,48.0,8.0,189.0,74.0,101.0,66.0,51.0
8556,2016-12-31 01:00:00,20161231,1,PM2.5,286.0,228.0,251.0,303.0,49.0,89.0,...,64.0,30.0,22.0,32.0,7.0,197.0,95.0,98.0,48.0,50.0
8557,2016-12-31 02:00:00,20161231,2,PM2.5,270.0,228.0,245.0,369.0,42.0,86.0,...,37.0,18.0,13.0,30.0,6.0,172.0,87.0,82.0,44.0,53.0
8558,2016-12-31 03:00:00,20161231,3,PM2.5,262.0,229.0,259.0,426.0,43.0,75.0,...,38.0,15.0,12.0,39.0,5.0,158.0,89.0,80.0,47.0,38.0
8559,2016-12-31 04:00:00,20161231,4,PM2.5,256.0,234.0,252.0,469.0,38.0,77.0,...,42.0,11.0,10.0,19.0,6.0,145.0,81.0,78.0,45.0,33.0
8560,2016-12-31 05:00:00,20161231,5,PM2.5,255.0,243.0,252.0,411.0,40.0,77.0,...,44.0,12.0,12.0,13.0,5.0,135.0,80.0,75.0,35.0,35.0
8561,2016-12-31 06:00:00,20161231,6,PM2.5,238.0,241.0,261.0,360.0,41.0,72.0,...,34.0,10.0,12.0,9.0,6.0,130.0,81.0,74.0,31.0,37.0
8562,2016-12-31 07:00:00,20161231,7,PM2.5,216.0,245.0,269.0,338.0,43.0,69.0,...,35.0,11.0,10.0,9.0,5.0,125.0,84.0,78.0,31.0,32.0
8563,2016-12-31 08:00:00,20161231,8,PM2.5,196.0,246.0,282.0,315.0,43.0,82.0,...,33.0,9.0,14.0,17.0,7.0,127.0,92.0,77.0,29.0,34.0
8564,2016-12-31 09:00:00,20161231,9,PM2.5,193.0,253.0,323.0,298.0,43.0,90.0,...,38.0,12.0,9.0,14.0,9.0,139.0,121.0,93.0,30.0,34.0
8565,2016-12-31 10:00:00,20161231,10,PM2.5,213.0,266.0,327.0,316.0,44.0,80.0,...,47.0,12.0,12.0,31.0,18.0,160.0,157.0,103.0,34.0,40.0
8566,2016-12-31 11:00:00,20161231,11,PM2.5,213.0,276.0,349.0,336.0,45.0,74.0,...,49.0,10.0,10.0,43.0,21.0,185.0,160.0,128.0,35.0,41.0
8567,2016-12-31 12:00:00,20161231,12,PM2.5,222.0,293.0,355.0,343.0,43.0,62.0,...,60.0,9.0,12.0,37.0,18.0,182.0,126.0,121.0,29.0,37.0
8568,2016-12-31 13:00:00,20161231,13,PM2.5,249.0,316.0,362.0,386.0,45.0,55.0,...,53.0,12.0,20.0,23.0,7.0,184.0,104.0,119.0,18.0,37.0
8569,2016-12-31 14:00:00,20161231,14,PM2.5,278.0,326.0,378.0,391.0,54.0,56.0,...,55.0,13.0,20.0,12.0,5.0,177.0,57.0,108.0,14.0,30.0
8570,2016-12-31 15:00:00,20161231,15,PM2.5,331.0,335.0,379.0,397.0,61.0,59.0,...,51.0,14.0,14.0,10.0,3.0,179.0,33.0,91.0,10.0,27.0
8571,2016-12-31 16:00:00,20161231,16,PM2.5,360.0,339.0,384.0,374.0,64.0,63.0,...,46.0,9.0,17.0,3.0,4.0,185.0,31.0,96.0,6.0,27.0
8572,2016-12-31 17:00:00,20161231,17,PM2.5,352.0,339.0,370.0,335.0,109.0,92.0,...,66.0,9.0,11.0,8.0,5.0,210.0,35.0,104.0,5.0,29.0
8573,2016-12-31 18:00:00,20161231,18,PM2.5,352.0,335.0,364.0,289.0,126.0,112.0,...,86.0,11.0,12.0,22.0,7.0,244.0,46.0,122.0,12.0,28.0
8574,2016-12-31 19:00:00,20161231,19,PM2.5,368.0,307.0,365.0,264.0,135.0,107.0,...,85.0,12.0,17.0,34.0,7.0,251.0,63.0,145.0,27.0,32.0
8575,2016-12-31 20:00:00,20161231,20,PM2.5,384.0,269.0,396.0,234.0,150.0,101.0,...,129.0,14.0,22.0,47.0,11.0,250.0,66.0,151.0,41.0,53.0
8576,2016-12-31 22:00:00,20161231,22,PM2.5,432.0,225.0,402.0,233.0,101.0,116.0,...,84.0,8.0,46.0,113.0,9.0,225.0,78.0,153.0,45.0,63.0
8577,2016-12-31 23:00:00,20161231,23,PM2.5,436.0,216.0,294.0,234.0,88.0,108.0,...,79.0,10.0,43.0,87.0,7.0,214.0,99.0,154.0,43.0,56.0

In [6]:
data.set_index(['new_date'],inplace=True)

In [7]:
data_copy = data.drop(['date','hour','type'],axis=1)

In [8]:
data_copy.shape

(8578, 97)

In [9]:
from sklearn.impute import KNNImputer

In [10]:
imputer = KNNImputer(n_neighbors=3)

In [11]:
for each in data_copy.columns:
    data_copy[each]=imputer.fit_transform(data_copy[[each]])

In [13]:
data_copy.shape

(8578, 97)

In [14]:
path_2 = '../../data/air_data/geo_distance.csv'

In [15]:
distance = pd.read_csv(path_2)

In [16]:
distance.head()

,city,station name,province,station_id,lat,lon,Elevation (m),geometry,geo_wgs,distance2Shanghai
0,Beijing,北京,北京,545110,39.48,116.28,32.5,POINT (116.28 39.48),POINT (116.28 39.48),1031.741531
1,Tianjin,天津,天津,545270,39.05,117.03,4.3,POINT (117.03 39.05),POINT (117.03 39.05),960.310172
2,Tangshan,唐山,河北,545340,39.39,118.06,24.5,POINT (118.06 39.39),POINT (118.06 39.39),962.432780
3,Baoding,保定,河北,546020,38.44,115.29,17.9,POINT (115.29 38.44),POINT (115.29 38.44),978.242903
4,Zhangjiakou,张家口,河北,544010,40.46,114.55,774.1,POINT (114.55 40.46),POINT (114.55 40.46),1199.876168

In [17]:
distance.shape

(96, 10)

In [20]:
data_copy.shape

(8578, 97)

In [21]:
shanghai=pd.DataFrame(data_copy['Shanghai'].iloc[8:])

In [24]:
# shanghai

In [25]:
other_city = data_copy.drop(columns=['Shanghai']).iloc[:-8]

In [26]:
# other_city.columns

In [27]:
# for i in range(len(other_city.columns))[:1]:
#     other_city= other_city.iloc[:,i]-shanghai

In [33]:
other_city.head()

,Beijing,Tianjin,Tangshan,Baoding,Zhangjiakou,Chengde,Xingtai,Taiyuan,Hohehot,Shenyang,...,Zhaotong,Lijiang,Lincang,Qamdo,Nyingchi,Hanzhong,Yulin,Ankang,Zhangye,Jiuquan
new_date,,,,,,,,,,,,,,,,,,,,,
2016-01-01 00:00:00,171.0,169.0,75.090197,92.246553,73.0,75.0,86.796495,200.0,38.950152,183.0,...,74.0,11.0,15.0,49.0,8.0,202.0,116.0,207.0,53.0,66.0
2016-01-01 01:00:00,167.0,161.0,279.000000,301.000000,53.0,78.0,163.000000,202.0,107.000000,143.0,...,93.0,16.0,24.0,3.0,5.0,203.0,119.0,202.0,47.0,44.0
2016-01-01 02:00:00,158.0,150.0,261.000000,321.000000,47.0,64.0,176.000000,155.0,109.000000,102.0,...,150.0,13.0,25.0,4.0,4.0,199.0,118.0,208.0,38.0,43.0
2016-01-01 03:00:00,147.0,137.0,198.000000,303.000000,43.0,58.0,187.000000,156.0,88.000000,80.0,...,52.0,20.0,36.0,1.0,15.0,188.0,122.0,219.0,30.0,33.0
2016-01-01 04:00:00,134.0,126.0,162.000000,211.000000,40.0,59.0,197.000000,130.0,85.000000,77.0,...,52.0,19.0,30.0,2.0,10.0,190.0,94.0,194.0,25.0,26.0

In [44]:
shanghai.head()

                     Shanghai
new_date
2016-01-01 08:00:00      54.0
2016-01-01 09:00:00      68.0
2016-01-01 10:00:00      65.0
2016-01-01 11:00:00      57.0
2016-01-01 12:00:00      51.0

In [42]:
shanghai[["Shanghai"]].values

array([[54.],
       [68.],
       [65.],
       ...,
       [36.],
       [35.],
       [38.]])

In [30]:
# bj_sh_list= []
# def get_pm25_df():
#     for city in set(list(distance['city'].values)):
#         for i in range(len(data_copy.columns)):
#             if data_copy.columns[i] == city:
#                 for i in range(len(data_copy.index)):
#                     bj_sh_list.append(data_copy["Shanghai"][i+8:]- data_copy[f"{city}"][i:])
#     return bj_sh_list

In [ ]:
list(distance['city'].values)

In [47]:
shanghai.head()

                     Shanghai
new_date
2016-01-01 08:00:00      54.0
2016-01-01 09:00:00      68.0
2016-01-01 10:00:00      65.0
2016-01-01 11:00:00      57.0
2016-01-01 12:00:00      51.0

In [50]:
import numpy as np
shanghai2 = shanghai.copy()
for city in other_city.columns:
    numpy_city = np.array(shanghai.Shanghai) - np.array(other_city[city])
    shanghai2[city] = numpy_city
shanghai2.head()

,Shanghai,Beijing,Tianjin,Tangshan,Baoding,Zhangjiakou,Chengde,Xingtai,Taiyuan,Hohehot,...,Zhaotong,Lijiang,Lincang,Qamdo,Nyingchi,Hanzhong,Yulin,Ankang,Zhangye,Jiuquan
new_date,,,,,,,,,,,,,,,,,,,,,
2016-01-01 08:00:00,54.0,-117.0,-115.0,-21.090197,-38.246553,-19.0,-21.0,-32.796495,-146.0,15.049848,...,-20.0,43.0,39.0,5.0,46.0,-148.0,-62.0,-153.0,1.0,-12.0
2016-01-01 09:00:00,68.0,-99.0,-93.0,-211.000000,-233.000000,15.0,-10.0,-95.000000,-134.0,-39.000000,...,-25.0,52.0,44.0,65.0,63.0,-135.0,-51.0,-134.0,21.0,24.0
2016-01-01 10:00:00,65.0,-93.0,-85.0,-196.000000,-256.000000,18.0,1.0,-111.000000,-90.0,-44.000000,...,-85.0,52.0,40.0,61.0,61.0,-134.0,-53.0,-143.0,27.0,22.0
2016-01-01 11:00:00,57.0,-90.0,-80.0,-141.000000,-246.000000,14.0,-1.0,-130.000000,-99.0,-31.000000,...,5.0,37.0,21.0,56.0,42.0,-131.0,-65.0,-162.0,27.0,24.0
2016-01-01 12:00:00,51.0,-83.0,-75.0,-111.000000,-160.000000,11.0,-8.0,-146.000000,-79.0,-34.000000,...,-1.0,32.0,21.0,49.0,41.0,-139.0,-43.0,-143.0,26.0,25.0

In [51]:
shanghai2.to_csv('../../data/air_data/pm25_8hours.csv')

In [52]:
shanghai_24h=pd.DataFrame(data_copy['Shanghai'].iloc[24:])

In [54]:
other_city_24h = data_copy.drop(columns=['Shanghai']).iloc[:-24]

In [55]:
import numpy as np
shanghai_24 = shanghai_24h.copy()
for city in other_city_24h.columns:
    numpy_city24 = np.array(shanghai_24.Shanghai) - np.array(other_city_24h[city])
    shanghai_24[city] = numpy_city24
shanghai_24.head()

,Shanghai,Beijing,Tianjin,Tangshan,Baoding,Zhangjiakou,Chengde,Xingtai,Taiyuan,Hohehot,...,Zhaotong,Lijiang,Lincang,Qamdo,Nyingchi,Hanzhong,Yulin,Ankang,Zhangye,Jiuquan
new_date,,,,,,,,,,,,,,,,,,,,,
2016-01-02 00:00:00,67.0,-104.0,-102.0,-8.090197,-25.246553,-6.0,-8.0,-19.796495,-133.0,28.049848,...,-7.0,56.0,52.0,18.0,59.0,-135.0,-49.0,-140.0,14.0,1.0
2016-01-02 01:00:00,65.0,-102.0,-96.0,-214.000000,-236.000000,12.0,-13.0,-98.000000,-137.0,-42.000000,...,-28.0,49.0,41.0,62.0,60.0,-138.0,-54.0,-137.0,18.0,21.0
2016-01-02 02:00:00,66.0,-92.0,-84.0,-195.000000,-255.000000,19.0,2.0,-110.000000,-89.0,-43.000000,...,-84.0,53.0,41.0,62.0,62.0,-133.0,-52.0,-142.0,28.0,23.0
2016-01-02 03:00:00,65.0,-82.0,-72.0,-133.000000,-238.000000,22.0,7.0,-122.000000,-91.0,-23.000000,...,13.0,45.0,29.0,64.0,50.0,-123.0,-57.0,-154.0,35.0,32.0
2016-01-02 04:00:00,66.0,-68.0,-60.0,-96.000000,-145.000000,26.0,7.0,-131.000000,-64.0,-19.000000,...,14.0,47.0,36.0,64.0,56.0,-124.0,-28.0,-128.0,41.0,40.0

In [61]:
shanghai_24.to_csv('../../data/air_data/pm25_24hours.csv')

In [63]:
shanghai48=pd.DataFrame(data_copy['Shanghai'].iloc[48:])
other_city_48h = data_copy.drop(columns=['Shanghai']).iloc[:-48]
for city in other_city_48h.columns:
    numpy_city48 = np.array(shanghai48.Shanghai) - np.array(other_city_48h[city])
    shanghai48[city] = numpy_city48
shanghai48.head()

,Shanghai,Beijing,Tianjin,Tangshan,Baoding,Zhangjiakou,Chengde,Xingtai,Taiyuan,Hohehot,...,Zhaotong,Lijiang,Lincang,Qamdo,Nyingchi,Hanzhong,Yulin,Ankang,Zhangye,Jiuquan
new_date,,,,,,,,,,,,,,,,,,,,,
2016-01-03 00:00:00,148.0,-23.0,-21.0,72.909803,55.753447,75.0,73.0,61.203505,-52.0,109.049848,...,74.0,137.0,133.0,99.0,140.0,-54.0,32.0,-59.0,95.0,82.0
2016-01-03 01:00:00,151.0,-16.0,-10.0,-128.000000,-150.000000,98.0,73.0,-12.000000,-51.0,44.000000,...,58.0,135.0,127.0,148.0,146.0,-52.0,32.0,-51.0,104.0,107.0
2016-01-03 02:00:00,153.0,-5.0,3.0,-108.000000,-168.000000,106.0,89.0,-23.000000,-2.0,44.000000,...,3.0,140.0,128.0,149.0,149.0,-46.0,35.0,-55.0,115.0,110.0
2016-01-03 03:00:00,153.0,6.0,16.0,-45.000000,-150.000000,110.0,95.0,-34.000000,-3.0,65.000000,...,101.0,133.0,117.0,152.0,138.0,-35.0,31.0,-66.0,123.0,120.0
2016-01-03 04:00:00,160.0,26.0,34.0,-2.000000,-51.000000,120.0,101.0,-37.000000,30.0,75.000000,...,108.0,141.0,130.0,158.0,150.0,-30.0,66.0,-34.0,135.0,134.0

In [64]:
shanghai48.to_csv('../../data/air_data/pm25_48hours.csv')